### ISSUE TITLE
PersistentVolume for mysql-data

### ISSUE THREAD

**Issue by naveensrinivasan** [fabric8io/kubernetes-zipkin#92]
I was trying to run the `zipkin-starter-0.1.5-kubernetes.yml` in minikube and ran into an issue where the PVC was stuck in the pending mode. 

That is when I realized the yml file didn't have an entry for the PersistentVolume which was causing the PVC to be stuck forever. 

When I created an entry for the PersistentVolume things have started working.

**Comment by jimmidyson** [comment]
Glad you got it sorted.

Most Kubernetes deployments now use [dynamic provisioning](https://kubernetes.io/docs/user-guide/persistent-volumes/#dynamic) and [this post](http://blog.kubernetes.io/2016/10/dynamic-provisioning-and-storage-in-kubernetes.html) to provision PVs. If the YAML file had a PV in it, it becomes less portable so it is preferred to leave that out and either statically create the PV or use dynamic provisioning to create it.

**Comment by naveensrinivasan** [comment]
@jimmidyson Thanks.

IMHO either it would have to be documented in the `README.md` or fix the yml with the annotation like this 
``` yml
- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      project: "zipkin-mysql"
      version: "0.1.5"
      group: "io.fabric8.zipkin"
    name: "mysql-data"
    annotations:
     volume.alpha.kubernetes.io/storage-class: default
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "100Mi"
```

Thoughts?

**Comment by eschaef1** [comment]
I'm having a similar issue with OpenShift, however because the PVC is still pending, it doesn't seem as though there is a YAML available for me to edit, or any option to create one. I'm very new to OpenShift, so does anyone have any suggestions? Thanks!

**Comment by simongui** [comment]
I'm having the same issue on `minikube`. Even after adding the annotation @naveensrinivasan mentioned.

```
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  4m		4m		1	{default-scheduler }			Normal		Scheduled	Successfully assigned zipkin-mysql-285018599-1frrk to minikube
  2m		25s		2	{kubelet minikube}			Warning		FailedMount	Unable to mount volumes for pod "zipkin-mysql-285018599-1frrk_default(cb28ad3c-0837-11e7-b949-96d251eab0c6)": timeout expired waiting for volumes to attach/mount for pod "default"/"zipkin-mysql-285018599-1frrk". list of unattached/unmounted volumes=[mysql-data]
  2m		25s		2	{kubelet minikube}			Warning		FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"zipkin-mysql-285018599-1frrk". list of unattached/unmounted volumes=[mysql-data]
```

**Comment by naveensrinivasan** [comment]
@simongui What does `kubectl get pv` looks like?

**Comment by simongui** [comment]
I got it to work. I had to create a persistent volume before deploying Zipkin.

mysql-data.yml
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-data
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
```

```
kubectl create -f mysql-data.yml
```

I'm new to Kubernetes but I'm assuming this isn't a good volume to create because it's pointed to `/tmp/data`. Suggestions?

**Comment by rafabene** [comment]
Following as I'm having the same problem to deploy in OpenShift/CDK

**Comment by naveensrinivasan** [comment]
I was able to get it working 
```
 ~/temp  k8s-minikube/zipkin  k create namespace zipkintest
namespace "zipkintest" created
 ~/temp  k8s-minikube/zipkin  kubectl config set-context minikube --namespace=zipkintest
Context "minikube" set.
 ~/temp  k8s-minikube/zipkintest 
 ~/temp  k8s-minikube/zipkintest  k apply -f zipkin-starter-0.1.5-kubernetes.yml
service "kafka" created
service "zipkin" created
service "zipkin-mysql" created
service "zookeeper" created
persistentvolumeclaim "mysql-data" created
configmap "zipkin-mysql-cnf" created
configmap "zipkin-mysql-initdb" created
deployment "kafka" created
deployment "zipkin" created
deployment "zipkin-mysql" created
deployment "zookeeper" created
 ~/temp  k8s-minikube/zipkintest  k get pv
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                   REASON    AGE
pvc-4b5e428d-10fa-11e7-b903-080027cac7d7   100Mi      RWO           Delete          Bound     zipkintest/mysql-data             16s
 ~/temp  k8s-minikube/zipkintest  k get po
NAME                            READY     STATUS    RESTARTS   AGE
kafka-2002085703-3jhw8          1/1       Running   0          27s
zipkin-358939735-cg4r3          0/1       Running   0          27s
zipkin-mysql-3963011279-zw8m0   1/1       Running   0          27s
zookeeper-650666963-x3jcm       1/1       Running   0          27s
 ~/temp  k8s-minikube/zipkintest  kubectl get po
NAME                            READY     STATUS    RESTARTS   AGE
kafka-2002085703-3jhw8          1/1       Running   0          40s
zipkin-358939735-cg4r3          1/1       Running   0          40s
zipkin-mysql-3963011279-zw8m0   1/1       Running   0          40s
zookeeper-650666963-x3jcm       1/1       Running   0          40s    
```


Here is the YAML https://gist.github.com/naveensrinivasan/58ef741faa69f18fafb2c3e0df95d62f

**Comment by simongui** [comment]
What did you change to make this work @naveensrinivasan? I tried to add this to the `minimal` yaml file but it still fails.

```
- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      project: "zipkin-mysql"
      version: "0.1.5"
      group: "io.fabric8.zipkin"
    name: "mysql-data"
    annotations:
      volume.beta.kubernetes.io/storage-class: default
```

**Comment by naveensrinivasan** [comment]
Did you have a look at the Yaml in the gist?

**Comment by simongui** [comment]
Yeah, the main thing I see different is what I pasted. Was there anything more? I'm also having difficulty deploying this version of the YAML from your gist. It seems sometimes all the pods come up except the Zipkin one. Almost like it's trying to connect to dependent services and fails before they come up.

**Comment by naveensrinivasan** [comment]
What is the error from the pod logs?

**Comment by simongui** [comment]
```
2017-04-02T20:56:38.289782022Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289785277Z 	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:105) ~[spring-boot-actuator-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
2017-04-02T20:56:38.289788386Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2017-04-02T20:56:38.289791660Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289794780Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289798168Z 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2017-04-02T20:56:38.289801222Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2017-04-02T20:56:38.289804249Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289807295Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289810452Z 	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:89) ~[spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2017-04-02T20:56:38.289814239Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2017-04-02T20:56:38.289817428Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289820553Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289823772Z 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) ~[spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2017-04-02T20:56:38.289827058Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2017-04-02T20:56:38.289833742Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289839337Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289844063Z 	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:107) ~[spring-boot-actuator-1.4.1.RELEASE.jar!/:1.4.1.RELEASE]
2017-04-02T20:56:38.289847181Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
2017-04-02T20:56:38.289854146Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289857472Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289860606Z 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289863727Z 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289866797Z 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289870024Z 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289873001Z 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289876062Z 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289913220Z 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289917976Z 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289921452Z 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289924905Z 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289928200Z 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289931316Z 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289934639Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
2017-04-02T20:56:38.289937630Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
2017-04-02T20:56:38.289948504Z 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.5.jar!/:8.5.5]
2017-04-02T20:56:38.289952552Z 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
```

**Comment by simongui** [comment]
Oh weird, after 30-60mins I refreshed and it finally shows up as running. That's a really long time.

**Comment by simongui** [comment]
Scratch that, it's still not running.
```
kubectl get pods
NAME                           READY     STATUS    RESTARTS   AGE
kafka-1764556007-hk3f0         1/1       Running   0          1h
zipkin-1572713903-vp7sn        0/1       Running   0          1h
zipkin-mysql-285018599-pk6bk   1/1       Running   1          1h
zookeeper-3120290255-nv64q     1/1       Running   0          1h
```

**Comment by cmoulliard** [comment]
Here is what I did to delete/create a new pvc

```
Versions
- Minishift : 1.0.1
- OpenShift Origin : 1.5

minishift start
oc new-project zipkin
oc create -f http://repo1.maven.org/maven2/io/fabric8/zipkin/zipkin-starter-minimal/0.1.9/zipkin-starter-minimal-0.1.9-openshift.yml
oc delete pvc/mysql-data
cat << EOF | oc create -f - 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
EOF
```

**Comment by r4j4h** [comment]
To clarify, the problem issues for me were that `spec.volumeName` was defined so automatic provisioners failed as it tried to look up the existing volume.

Manually creating a volume with that name, or removing the volumeName before creating the resource should work, depending on usage of automatic PV provisioners.

**Comment by adrianchifor** [comment]
Hey guys, I have followed your suggestions but with no luck...the zipkin-mysql Pod keeps erroring:
```
Initializing database
2017-07-31T19:52:40.460188Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2017-07-31T19:52:40.460229Z 0 [Warning] 'NO_AUTO_CREATE_USER' sql mode was not set.
2017-07-31T19:52:40.462439Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2017-07-31T19:52:40.462527Z 0 [ERROR] Aborting
```

Any ideas?

**Comment by adrianchifor** [comment]
Ok, apparently on k8s there is this active issue with running mysql https://github.com/docker-library/mysql/issues/186. The solution is to add the following args to the `zipkin-mysql` Pod:
```
image: mysql:5.7
name: zipkin-mysql
readinessProbe:
  initialDelaySeconds: 5
  tcpSocket:
    port: 3306
args:
  - "--ignore-db-dir=lost+found"
```

**Comment by adriancole** [comment]
>
> Ok, apparently on k8s there is this active issue with running mysql
> docker-library/mysql#186
> <https://github.com/docker-library/mysql/issues/186>. The solution is to
> add the following args to the zipkin-mysql Pod:
>
Thanks for following up

**Comment by davgordo** [comment]
I think the small change proposed in #118 would save a lot of confusion. For example, a minishift user will automatically have PVs that are appropriate for the template, but they won't bind because they're not named `mysql-data`. It seems overly prescriptive to me to name the volume.

**Comment by 2ZZ** [comment]
I had to specify the storageClassName to get the PVC to bind to the PV

```apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /data/mysql-data/
```
